### ISSUE TITLE
Use a build system to publish the project and make it easily installable by others

### ISSUE THREAD

**Issue by MiguelGuthridge** [dimentorium/Flappy#1]
Thanks for your work making such an awesome tool! It looks like it'll be very useful for lots of people!

To make it a little easier to use, it would be worthwhile publishing the project so that it can be installed by other users with `pip`.

* [ ] Decide on a the name to publish the project under (since `flappy` is taken on [pypi.org](https://pypi.org/search/?q=flappy&o=)). Perhaps `flappi`?
* [ ] Set up a build system which can keep track of the project's dependencies (my personal preference for this is [Poetry](https://python-poetry.org/), but there are plenty of other options).
* [ ] Create a simple CLI script that installs/removes the device script to the user's `Image-Line/FL Studio/Settings/Hardware` folder
* [ ] Publish the tool as a package, so that users can `pip install [project name]` then run the setup script and have things work out of the box!

Thanks again for creating such a cool tool! Hopefully these steps will make it even more useful for everyone!

If you need a hand with any of them, I'll be very happy to help out!

**Comment by dimentorium** [comment]
Hi Michael,
to be honest, I wrote this because of a small idea I had. It did not work out as exspected, but I thought I share the code for others, so no one needs to reinvent the wheel.
Setting it up as you wrote would require lots of time for me (as I never did that), which I definately not have.
So I would prefer to leave it as is, and if you or anyone else wants to create the build, feel free to do so. I am ok, if my code is cloned ;-)
